service: email-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10

  environment:
    SMTP_EMAIL: harshpandey59365@gmail.com
    SMTP_PASSWORD: cxxrpbrqlmikaqzb

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post